<?php
/**
 * @package Serializer
 */

/**
 * Read a value generated by a callback function
 *
 * @package Serializer
 */
class NethGui_Serializer_CallbackSerializer implements NethGui_Serializer_SerializerInterface
{

    private $callable;       

    public function __construct($callable)
    {
        if ( ! is_callable($callable)) {
            throw new InvalidArgumentException('Invalid callback function');
        }

        $this->callable = $callable;
    }

    public function read()
    {
        return call_user_func($this->callable);
    }

    public function write($value)
    {
        // PASS - readonly serializer
    }

}
