<?php
namespace Nethgui\Controller;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-08-23 at 13:40:11.
 */
class RequestTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Request
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $d = array_replace_recursive(
            // The PATH_INFO
            array('a' => array('b' => array('c' => array('d' => array())))),
            // GET vars
            array('a' => array('b' => array('c' => array('d' => array(
                            'v1' => 'g1',
                            'v2' => 'g2'
                        ))))),
            // POST vars
            array(
            'a' => array('b' => array('c' => array('d' => array(
                            'v1' => 'p1',
                            'v3' => 'p3'
                        )))),
            'lang' => 'it',
            'x' => array('w1' => "1", 'w2' => "2")
            )
        );
        $this->object = new Request($d);
    }

    /**
     * @covers Nethgui\Controller\Request::setSession
     * @todo   Implement testSetSession().
     */
    public function testSetSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Nethgui\Controller\Request::hasParameter
     * @todo   Implement testHasParameter().
     */
    public function testHasParameter()
    {
        $this->assertTrue($this->object->hasParameter('a'));
        $this->assertFalse($this->object->hasParameter('z'));
    }

    /**
     * @covers Nethgui\Controller\Request::isEmpty
     * @todo   Implement testIsEmpty().
     */
    public function testIsEmpty()
    {
        $this->assertFalse($this->object->isEmpty());
    }

    /**
     * @covers Nethgui\Controller\Request::isMutation
     * @todo   Implement testIsMutation().
     */
    public function testIsMutation()
    {
        $this->assertFalse($this->object->isMutation());
    }

    /**
     * @covers Nethgui\Controller\Request::getParameterNames
     * @todo   Implement testGetParameterNames().
     */
    public function testGetParameterNames()
    {
        $this->assertEquals(array('a', 'lang', 'x'), $this->object->getParameterNames());
    }

    /**
     * @covers Nethgui\Controller\Request::getParameter
     * @todo   Implement testGetParameter().
     */
    public function testGetParameter()
    {
        $this->assertEquals('it', $this->object->getParameter('lang'));
    }

    /**
     * @covers Nethgui\Controller\Request::spawnRequest
     * @todo   Implement testSpawnRequest().
     */
    public function testSpawnRequest()
    {
        $r = $this->object->spawnRequest('a');
        $this->assertEquals(array('b' => array('c' => array('d' => array(
                        'v1' => 'p1',
                        'v2' => 'g2',
                        'v3' => 'p3'
                    )))), $r->toArray());
        $this->assertEquals(array('b', 'c', 'd'), $r->getPath());
    }

    /**
     * @covers Nethgui\Controller\Request::getUser
     * @todo   Implement testGetUser().
     */
    public function testGetUser()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Nethgui\Controller\Request::getPath
     * @todo   Implement testGetPath().
     */
    public function testGetPath()
    {
        $this->assertEquals(array('a', 'b', 'c', 'd'), $this->object->getPath());
    }

    /**
     * @covers Nethgui\Controller\Request::getAttribute
     * @todo   Implement testGetAttribute().
     */
    public function testGetAttribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Nethgui\Controller\Request::setAttribute
     * @todo   Implement testSetAttribute().
     */
    public function testSetAttribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Nethgui\Controller\Request::getExtension
     * @todo   Implement testGetExtension().
     */
    public function testGetExtension()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Nethgui\Controller\Request::getLanguage
     * @todo   Implement testGetLanguage().
     */
    public function testGetLanguage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Nethgui\Controller\Request::isValidated
     * @todo   Implement testIsValidated().
     */
    public function testIsValidated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Nethgui\Controller\Request::getArgument
     * @todo   Implement testGetArgument().
     */
    public function testGetArgument()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Nethgui\Controller\Request::getArgumentNames
     * @todo   Implement testGetArgumentNames().
     */
    public function testGetArgumentNames()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Nethgui\Controller\Request::hasArgument
     * @todo   Implement testHasArgument().
     */
    public function testHasArgument()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Nethgui\Controller\Request::getLog
     * @todo   Implement testGetLog().
     */
    public function testGetLog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Nethgui\Controller\Request::setLog
     * @todo   Implement testSetLog().
     */
    public function testSetLog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Nethgui\Controller\Request::toArray
     * @todo   Implement testToArray().
     */
    public function testToArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
