<?php
/**
 * @package Tests
 * @subpackage Unit
 */

/**
 * Test class for NethGui_Adapter_TabularValueAdapter.
 * Generated by PHPUnit on 2011-03-21 at 17:56:35.
 * @package Tests
 * @subpackage Unit
 */
class NethGui_Adapter_TabularValueAdapterTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var NethGui_Adapter_TabularValueAdapter
     */
    protected $object;
    /**
     *
     * @var NethGui_Serializer_SerializerInterface
     */
    private $serializer;


    protected function setUp()
    {
        $this->serializer = $this->getMockBuilder('NethGui_Serializer_KeySerializer')
            ->disableOriginalConstructor()
            ->getMock();
               
        $this->serializer->expects($this->any())->method('read')
            ->will($this->returnValue('1A/1B/1C,2A/2B/2C,3A/3B/3C'));

        $innerAdapter = new NethGui_Adapter_ArrayAdapter(',', $this->serializer);

        $this->object = new NethGui_Adapter_TabularValueAdapter($innerAdapter, '/');
    }

    public function testCount()
    {
        $this->assertEquals(3, $this->object->count());
    }

    public function testDelete()
    {
        $this->object->delete();
        $this->assertEquals(0, $this->object->count());
    }

    public function testGet()
    {
        $compareMatrix = array(
            array('1A', '1B', '1C'),
            array('2A', '2B', '2C'),
            array('3A', '3B', '3C'),
        );

        $i = 0;

        foreach ($this->object as $row) {
            $this->assertEquals($row, $compareMatrix[$i ++]);
        }
    }

    public function testSet()
    {
        $compareMatrix = array(
            array('1A', '1B', '1C'),
            array('2A', '2B', '2C'),
        );

        $this->object->set($compareMatrix);

        $i = 0;

        foreach ($this->object as $row) {
            $this->assertEquals($row, $compareMatrix[$i ++]);
        }
    }

    public function testSaveModified()
    {
        $this->object[2] = array('0', '0', '0');

        $this->serializer->expects($this->once())
            ->method('write')
            ->with($this->equalTo('1A/1B/1C,2A/2B/2C,0/0/0'));

        $this->object->save();
    }

    public function testSaveNotModified()
    {
        $this->serializer->expects($this->never())
            ->method('write');
        $this->object->save();
    }

    public function testGetIterator()
    {
        $it = $this->object->getIterator();
        $this->assertEquals(3, $it->count());
    }

    public function testIsModified1()
    {
        $this->assertFalse($this->object->isModified());
        $this->object[2] = array('0', '0', '0');
        $this->assertTrue($this->object->isModified());
    }

    public function testIsModified2()
    {
        $this->testSaveModified();
        $this->assertFalse($this->object->isModified());
    }

    public function testOffsetExists()
    {           
        $this->assertTrue($this->object->offsetExists(0));
        $this->assertTrue($this->object->offsetExists(1));
        $this->assertTrue($this->object->offsetExists(2));
        $this->assertFalse($this->object->offsetExists(3));
        $this->assertFalse($this->object->offsetExists(-1));
        $this->assertFalse($this->object->offsetExists(''));        
    }

    public function testOffsetGet()
    {
       $this->assertTrue(is_array($this->object->offsetGet(0)));
       $this->assertTrue(is_array($this->object->offsetGet(1)));
       $this->assertTrue(is_array($this->object->offsetGet(2)));      
    }

    /**
     * @todo Implement testOffsetSet().
     */
    public function testOffsetSet()
    {
        $this->object->offsetSet(2, array('0', '0', '0'));
        $this->assertEquals(array('0', '0', '0'), $this->object[2]);
    }

    /**
     * @todo Implement testOffsetUnset().
     */
    public function testOffsetUnset()
    {
        $this->object->offsetUnset(2);
        $this->assertEquals(2, $this->object->count());
        $this->assertFalse($this->object->offsetExists(2));
    }

}

?>
