<?php
namespace Nethgui\Test\Unit\Nethgui\System;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-28 at 16:00:13.
 */
class SessionDatabaseTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \Nethgui\System\SessionDatabase
     */
    protected $object;

    protected function setUp()
    {
        $this->object = new \Nethgui\System\SessionDatabase;
    }



    /**
     * @covers Nethgui\System\SessionDatabase::delProp
     * @todo   Implement testDelProp().
     */
    public function testDelProp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Nethgui\System\SessionDatabase::deleteKey
     * @todo   Implement testDeleteKey().
     */
    public function testDeleteKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Nethgui\System\SessionDatabase::getAll
     * @todo   Implement testGetAll().
     */
    public function testGetAll()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Nethgui\System\SessionDatabase::getKey
     * @todo   Implement testGetKey().
     */
    public function testGetKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Nethgui\System\SessionDatabase::getProp
     * @todo   Implement testGetProp().
     */
    public function testGetProp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Nethgui\System\SessionDatabase::getType
     * @todo   Implement testGetType().
     */
    public function testGetType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Nethgui\System\SessionDatabase::setKey
     * @todo   Implement testSetKey().
     */
    public function testSetKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Nethgui\System\SessionDatabase::setProp
     * @todo   Implement testSetProp().
     */
    public function testSetProp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Nethgui\System\SessionDatabase::setType
     * @todo   Implement testSetType().
     */
    public function testSetType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Nethgui\System\SessionDatabase::setSession
     * @todo   Implement testSetSession().
     */
    public function testSetSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}