<?php
/**
 */

/**
 * Test class for \Nethgui\Core\ParameterSet.
 * Generated by PHPUnit on 2011-03-24 at 15:56:58.
 */
class \Nethgui\Core\ParameterSetEmptyTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var \Nethgui\Core\ParameterSet
     */
    protected $object;

    protected function setUp()
    {
        $this->object = new \Nethgui\Core\ParameterSet;
    }

    public function testCount()
    {
        $this->assertEquals(0, $this->object->count());
    }

    public function offsetProvider()
    {
        return array(
            array('a'),
            array('b'),
            array('c'),
            array('d'),
        );
    }

    /**
     * @dataProvider offsetProvider
     */
    public function testOffsetExists($offset)
    {
        $this->assertFalse($this->object->offsetExists($offset));
    }

    /**
     * @dataProvider offsetProvider
     * @expectedException PHPUnit_Framework_Error_Notice
     */
    public function testOffsetGet($offset)
    {
        $this->object->offsetGet($offset);
    }

    public function valuesProvider()
    {
        return array(
            array('a', '10'),
            array('b', '20'),
            array('c', '30'),
            array('d', '40'),
        );
    }

    /**
     * @dataProvider valuesProvider
     */
    public function testOffsetSet($offset, $value)
    {
        $this->object->offsetSet($offset, $value);
        $this->assertEquals($this->object->offsetGet($offset), $value);
    }

    /**
     * @dataProvider offsetProvider
     */
    public function testOffsetUnset($offset)
    {
        $this->object[$offset] = 'VALUE';
        unset($this->object[$offset]);
        $this->assertFalse(isset($this->object[$offset]));
    }

    public function testSave()
    {
        $this->assertEquals(0, $this->object->save());
    }

}

?>
