<?php

/**
 * Test class for NethGui_Module_RemoteAccess_RemoteManagement.
 * Generated by PHPUnit on 2011-03-16 at 15:53:04.
 */
class NethGui_Module_RemoteAccess_RemoteManagementTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var NethGui_Module_RemoteAccess_RemoteManagement
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new NethGui_Module_RemoteAccess_RemoteManagement;

        $configurationMock = $this->getMock('NethGui_Core_SMEHostConfiguration');

        $configurationMock
            ->expects($this->any())
            ->method('setDb')
            ->will($this->returnValue($configurationMock));

        $configurationMock
            ->expects($this->any())
            ->method('getProp')
            ->will($this->returnValue('0.0.0.0'))
        ;

        $this->object->setHostConfiguration($configurationMock);

        $this->object->initialize();

        $request = $this->getMockBuilder("NethGui_Core_Request")
                ->disableOriginalConstructor()
                ->getMock()
        ;

        $request->expects($this->any())
            ->method('hasParameter')
        ;

        $this->object->bind($request);
    }

    /**
     * @todo Implement testProcess().
     */
    public function testProcess()
    {
        $this->object->process();
        

        $response = $this->getMockBuilder('NethGui_Core_Response')
                ->disableOriginalConstructor()
                ->getMock();

        $response->expects($this->once())
            ->method('setData')
            ->with(
                $this->logicalAnd(
                    $this->arrayHasKey('networkAddress'),
                    $this->arrayHasKey('networkMask')
                )
            )
        ;

        $this->object->prepareView($response);        
    }

}

?>
