<?php
/**
 * @package Tests
 * @subpackage Unit
 */

/**
 * Test class for NethGui_Core_ParameterSet.
 * Generated by PHPUnit on 2011-03-24 at 15:56:58.
 * @package Tests
 * @subpackage Unit
 */
class NethGui_Core_ParameterSetWithAdaptersTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var NethGui_Core_ParameterSet
     */
    protected $object;

    protected function setUp()
    {
        $this->object = new NethGui_Core_ParameterSet;

        $this->arrayAdapter = $this->getMockBuilder('NethGui_Adapter_ArrayAdapter')
                ->disableOriginalConstructor()
                ->getMock();

        $this->scalarAdapter = $this->getMockBuilder('NethGui_Adapter_ScalarAdapter')
                ->disableOriginalConstructor()
                ->getMock();

        $this->object->register($this->arrayAdapter, 'arrayAdapter');
        $this->object->register($this->scalarAdapter, 'scalarAdapter');
        $this->object['inner'] = $this->getMock('NethGui_Core_ParameterSet');
        $this->object['pi'] = 3.14;
    }

    public function testCount()
    {
        $this->assertEquals(4, $this->object->count());
    }

    public function testUserScalarAdapter()
    {
        $this->scalarAdapter->expects($this->once())
            ->method('set')
            ->with('VALUE');

        $this->object['scalarAdapter'] = 'VALUE';
    }

    public function testUseArrayAdapter()
    {
        $this->arrayAdapter->expects($this->once())
            ->method('offsetSet')
            ->with(1, 'NEW');

        $this->arrayAdapter->expects($this->exactly(2))
            ->method('get')
            ->will($this->returnValue($this->arrayAdapter));

        $this->arrayAdapter->expects($this->once())
            ->method('offsetGet')
            ->with(1)
            ->will($this->returnValue('VALUE'));


        $this->assertEquals('VALUE', $this->object['arrayAdapter'][1]);

        $this->object['arrayAdapter'][1] = 'NEW';
    }

    public function testSave()
    {
        $this->arrayAdapter->expects($this->once())
            ->method('save');

        $this->scalarAdapter->expects($this->once())
            ->method('save');

        $this->object['inner']->expects($this->once())
            ->method('save');

        $this->object->save();
    }

}

?>
