<?php

/**
 * Test class for NethGui_Core_ArrayAdapter.
 * Generated by PHPUnit on 2011-03-23 at 17:50:37.
 */
class NethGui_Core_ArrayAdapterTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var NethGui_Core_ArrayAdapter
     */
    protected $fixture;
    /**
     *
     * @var NethGui_Core_SerializerInterface
     */
    private $serializer;

    protected function setUp()
    {

        $this->serializer = $this->getMockBuilder('NethGui_Core_KeySerializer')
                ->disableOriginalConstructor()
                ->getMock();

        $this->serializer->expects($this->once())
            ->method('read')
            ->withAnyParameters()
            ->will($this->returnValue('ONE,TWO,THREE'));

        $this->fixture = new NethGui_Core_ArrayAdapter(',', $this->serializer);
    }

    public function testGet()
    {
        $this->assertEquals('ONE', $this->fixture->get()->offsetGet(0));
        $this->assertEquals('TWO', $this->fixture->get()->offsetGet(1));
        $this->assertEquals('THREE', $this->fixture->get()->offsetGet(2));
        $this->assertFalse($this->fixture->isModified());

        return $this->fixture;
    }

    /**
     * @expectedException NethGui_Exception_Adapter
     */
    public function testSet()
    {
        $this->fixture->set(array('A', 'B', 'C'));
        $this->assertEquals('A', $this->fixture[0]);
        $this->assertEquals('B', $this->fixture[1]);
        $this->assertEquals('C', $this->fixture[2]);
        $this->assertTrue($this->fixture->isModified());
        $this->fixture->set('FAIL');
    }

    public function testDelete()
    {
        $this->fixture->delete();
        $this->assertTrue($this->fixture->isModified());
        $this->assertNull($this->fixture[0]);
    }

    public function testIsModified()
    {
        $this->assertFalse($this->fixture->isModified());
        $this->fixture[0] = 'UNO';
        $this->assertTrue($this->fixture->isModified());

        return $this->fixture;
    }

    public function testSaveModified()
    {
        $this->fixture[0] = 'UNO';

        $this->serializer->expects($this->once())
            ->method('write')
            ->with('UNO,TWO,THREE');

        $this->fixture->save();
    }

    public function testSaveNotModified()
    {
        $this->serializer->expects($this->never())
            ->method('write');

        $v = $this->fixture[0];

        $this->assertEquals('ONE', $v);

        $this->fixture->save();
    }

    /**
     * @todo Resolve setUp() read expectation.
     *
     */
    public function testSaveUninitialized()
    {
        unset($this->serializer);

        $this->serializer = $this->getMockBuilder('NethGui_Core_KeySerializer')
                ->disableOriginalConstructor()
                ->getMock();

        $this->serializer->expects($this->never())
            ->method('write')
            ->withAnyParameters();

        $this->fixture->save();

        $this->markTestSkipped('TODO: Resolve setUp() read expectation.');
    }

    /**
     * @todo Implement testCount().
     */
    public function testCount()
    {
        $this->assertEquals(3, count($this->fixture));
        $this->fixture[] = 'FOUR';
        $this->assertEquals(4, count($this->fixture));
    }

    /**
     * @todo Implement testGetIterator().
     */
    public function testGetIterator()
    {
        $a = array('ONE', 'TWO', 'THREE');

        foreach ($this->fixture as $key => $value) {
            $this->assertEquals($a[$key], $value);
        }

        $this->fixture->delete();

        $i = 0;

        foreach ($this->fixture as $value) {
            $i ++;
        }

        $this->assertEquals(0, $i, 'iterator does not loop.');
    }

    public function testOffsetExists()
    {
        $this->assertTrue(isset($this->fixture[0]));
    }

    public function testOffsetGet()
    {
        $this->assertEquals('TWO', $this->fixture[1]);
    }

    public function testOffsetSet()
    {
        for ($i = 0; $i < count($this->fixture); $i ++ ) {
            $this->fixture[$i] = 'MODIFIED';
            $this->assertEquals('MODIFIED', $this->fixture[$i]);
        }

        $this->assertTrue($this->fixture->isModified());
    }

    public function testOffsetUnset()
    {
        $n = count($this->fixture);
        for ($i = 0; $i < $n; $i ++ ) {
            unset($this->fixture[$i]);
        }
        $this->assertEquals(0, count($this->fixture));
        $this->assertTrue($this->fixture->isModified());
    }

}

?>
