<?php
/**
 * @package Tests
 * @subpackage Unit
 */

/**
 * Test class for NethGui_Core_HostConfiguration.
 * Generated by PHPUnit on 2011-03-18 at 10:30:21.
 * @package Tests
 * @subpackage Unit
 */
class NethGui_Core_HostConfigurationTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var NethGui_Core_HostConfiguration
     */
    protected $object;

    /**
     * Sets up the fixture
     */
    protected function setUp()
    {
        $this->object = new NethGui_Core_HostConfiguration(new NethGui_Core_AlwaysAuthenticatedUser());
        $this->object->setPolicyDecisionPoint(new NethGui_Authorization_PermissivePolicyDecisionPoint());
    }

    public function testPdp()
    {
        $db = $this->object->getDatabase('testdb');
        $this->assertSame($this->object->getPolicyDecisionPoint(), $db->getPolicyDecisionPoint());
    }

    /**
     * Asserts a database object interface has the same PDP of the fixture.
     */
    public function testGetDatabase()
    {
        $db = $this->object->getDatabase('testdb');
        $this->assertInstanceOf('NethGui_Core_ConfigurationDatabase', $db, $message);
    }

    /**
     *
     */
    public function testSignalEvent()
    {
        $this->assertEquals(false, $this->object->signalEvent("not-exist-event"));
        $this->assertEquals(true, $this->object->signalEvent("nethgui-test"));
    }

    public function testGetMapAdapter()
    {
        $adapter = $this->object->getMapAdapter(
                array($this, 'readCallback'),
                array($this, 'writeCallback'),
                array(
                    array('testdb', 'testkey1'),
                    array('testdb', 'testkey2', 'testpropA'),
                    array('testdb', 'testkey3', 'testpropB'),
                )
        );
        $this->assertInstanceOf('NethGui_Adapter_AdapterInterface', $adapter);
    }

    public function readCallback($key1, $propA, $propB)
    {
        return implode(',', array($key1, $propA, $propB));
    }

    public function writeCallback($value)
    {
        return explode(',', $value);
    }

    public function testGetIdentityAdapter()
    {
        $this->assertInstanceOf('NethGui_Adapter_AdapterInterface', $this->object->getIdentityAdapter('testdb', 'testkey'));
        $this->assertInstanceOf('ArrayAccess', $this->object->getIdentityAdapter('testdb', 'testkey', NULL, ','));
    }

}

