<?php
/**
 * @package Tests
 * @subpackage Core
 */

/**
 * Test class for NethGui_Core_HostConfiguration.
 * Generated by PHPUnit on 2011-03-18 at 10:30:21.
 */
class NethGui_Core_HostConfigurationTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var NethGui_Core_HostConfiguration
     */
    protected $object;

    /**
     * Sets up the fixture
     */
    protected function setUp()
    {
        $this->object = new NethGui_Core_HostConfiguration(new NethGui_Core_AlwaysAuthenticatedUser());
        $this->object->setPolicyDecisionPoint(new NethGui_Authorization_PermissivePolicyDecisionPoint());
    }

    /**
     * Asserts a database object interface has the same PDP of the fixture.
     */
    public function testGetDatabase()
    {
        $db = $this->object->getDatabase('testdb');

        $this->assertInstanceOf('NethGui_Core_ConfigurationDatabase', $db, $message);
        $this->assertSame($this->object->getPolicyDecisionPoint(), $db->getPolicyDecisionPoint());

    }

   /**
    * 
    */
   public function testSignalEvent()
   {
        $this->assertEquals(false,$this->object->signalEvent("not-exist-event"));
        $this->assertEquals(true,$this->object->signalEvent("remoteaccess-update"));
   }
}

