<?php

require_once '/var/www/html/devg/NethGui/Core/MockHostConfiguration.php';

/**
 * Test class for NethGui_Core_MockHostConfiguration.
 * Generated by PHPUnit on 2011-03-04 at 09:43:03.
 */
class NethGui_Core_MockHostConfigurationTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var NethGui_Core_MockHostConfiguration
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new NethGui_Core_MockHostConfiguration('testdb');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testSetPolicyDecisionPoint().
     */
    public function testSetPolicyDecisionPoint()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetPolicyDecisionPoint().
     */
    public function testGetPolicyDecisionPoint()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetUser().
     */
    public function testSetUser()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetKey().
     */
    public function testGetKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetKey().
     */
    public function testSetKey()
    {
        $props = array("FirstProp" => "firstvalue", "SecondProp" => "2ndvalue");
        $this->assertEquals(true,$this->object->setKey("testkey","service",$props));
    }

    /**
     * @todo Implement testDeleteKey().
     */
    public function testDeleteKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetType().
     */
    public function testGetType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetType().
     */
    public function testSetType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetProp().
     */
    public function testGetProp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetProp().
     */
    public function testSetProp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testDelProp().
     */
    public function testDelProp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
