<?php
/**
 * @package Tests
 * @subpackage Unit
 */

/**
 * Test class for NethGui_Core_PropSerializer.
 * Generated by PHPUnit on 2011-03-24 at 15:56:48.
 *
 * @package Tests
 * @subpackage Unit
 */
class NethGui_Core_PropSerializerTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var NethGui_Core_PropSerializer
     */
    protected $object;

    protected function setUp()
    {
        $this->database = $this->getMockBuilder('NethGui_Core_ConfigurationDatabase')
                ->disableOriginalConstructor()
                ->getMock();

        $this->object = new NethGui_Core_PropSerializer($this->database, 'TestKey', 'TestProp');
    }

    public function testRead()
    {
        $this->database->expects($this->once())
            ->method('getProp')
            ->with('TestKey', 'TestProp')
            ->will($this->returnValue('OK'));


        $this->assertEquals('OK', $this->object->read());
    }

    public function testWriteValue()
    {
        $this->database->expects($this->once())
            ->method('setProp')
            ->with('TestKey', array('TestProp' => 'VALUE'))
            ->will($this->returnValue(TRUE));

        $this->object->write('VALUE');
    }

    public function testWriteDelete()
    {
        $this->database->expects($this->once())
            ->method('delProp')
            ->with('TestKey', array('TestProp'))
            ->will($this->returnValue(TRUE));

        $this->object->write(NULL);
    }

}

?>
