<?php

/**
 * Test class for NethGui_Core_ScalarAdapter.
 * Generated by PHPUnit on 2011-03-21 at 17:56:35.
 */
class NethGui_Core_ScalarAdapterTest extends PHPUnit_Framework_TestCase
{

    public function testGet1()
    {
        $fixture = false;
        $this->markTestIncomplete();
        return $fixture;
    }

    /**
     * @depends testGet1
     */
    public function testSet1(NethGui_Core_ScalarAdapter $fixture)
    {

        $this->markTestIncomplete();
        return $fixture;
    }

    /**
     * @depends testSet1
     */
    public function testDelete1(NethGui_Core_ScalarAdapter $fixture)
    {
        $this->markTestIncomplete();
        return $fixture;
    }

    /**
     * @depends testDelete1
     */
    public function testIsModified1(NethGui_Core_ScalarAdapter $fixture)
    {
        $this->markTestIncomplete();
        return $fixture;
    }

    /**
     * @depends testIsModified1
     */
    public function testSave1(NethGui_Core_ScalarAdapter $fixture)
    {
        $this->markTestIncomplete();
        return $fixture;
    }



}

?>
