<?php
/**
 * @package Tests
 * @subpackage Core
 */

/**
 * Test class for NethGui_Core_ScalarAdapter.
 * Generated by PHPUnit on 2011-03-21 at 17:56:35.
 */
class NethGui_Core_ScalarAdapterTest extends PHPUnit_Framework_TestCase
{

    /**
     *
     * @var NethGui_Core_SerializerInterface
     */
    private $serializer;
    /**
     *
     * @var NethGui_Core_ScalarAdapter
     */
    private $fixture;

    protected function setUp()
    {
        $this->serializer = $this->getMockBuilder('NethGui_Core_KeySerializer')
                ->disableOriginalConstructor()
                ->getMock();

        $this->serializer->expects($this->any())
            ->method('read')
            ->withAnyParameters()
            ->will($this->returnValue('ORIGINAL'));

        $this->fixture = new NethGui_Core_ScalarAdapter($this->serializer);
    }

    public function testGet()
    {
        $this->serializer->expects($this->once())
            ->method('read')
            ->withAnyParameters()
            ->will($this->returnValue('ORIGINAL'));

        $this->assertEquals('ORIGINAL', $this->fixture->get());
        $this->assertFalse($this->fixture->isModified());

        return $this->fixture;
    }

    public function testSet()
    {
        $this->fixture->set('MODIFIED');
        $this->assertEquals('MODIFIED', $this->fixture->get());
        $this->assertTrue($this->fixture->isModified());

        return $this->fixture;
    }

    /**
     *
     * @depends testSet
     * @param NethGui_Core_ScalarAdapter $changedFixture
     */
    public function testSaveModified($changedFixture)
    {
        $this->serializer->expects($this->never())
            ->method('write')
            ->withAnyParameters();

        $changedFixture->save();
    }

    /**
     * @depends testGet
     * @param NethGui_Core_ScalarAdapter $unchangedFixture
     */
    public function testSaveNotModified($unchangedFixture)
    {
        $this->serializer->expects($this->never())
            ->method('write')
            ->withAnyParameters();

        $unchangedFixture->save();
    }

    public function testSaveUninitialized()
    {
        $this->serializer->expects($this->never())
            ->method('write')
            ->withAnyParameters();

        $this->fixture->save();
    }

    public function testDelete()
    {
        $this->assertFalse($this->fixture->isModified());
        $this->fixture->delete();
        $this->assertTrue($this->fixture->isModified());
        $this->assertNull($this->fixture->get());
    }

    public function testToString()
    {
        $this->assertEquals('ORIGINAL', (String) $this->fixture);
    }

}

?>
