<?php
/**
 * @package Tests
 * @subpackage Core
 */

/**
 * Test class for NethGui_Core_Validator.
 * Generated by PHPUnit on 2011-04-01 at 16:22:41.
 * @package NethGuiFramework
 * @subpackage Core
 */
class NethGui_Core_ValidatorTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var NethGui_Core_Validator
     */
    protected $object;

    protected function setUp()
    {
        $this->object = new NethGui_Core_Validator;
    }

    /**
     * @todo Implement testOrValidator().
     */
    public function testOrValidator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testMemberOf().
     */
    public function testMemberOf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    public function testRegexpSuccess()
    {
        $this->object->regexp('/[0-9]+/');
        $this->assertTrue($this->object->evaluate('12345'));
    }

    public function testRegexpFail()
    {
        $this->object->regexp('/[0-9]+/');
        $this->assertFalse($this->object->evaluate('aaaaa'));
    }

    /**
     * @todo Implement testNotEmpty().
     */
    public function testNotEmpty()
    {
        $this->object->notEmpty();      
        $this->assertFalse($this->object->evaluate(''));
    }

    public function testForceResultTrue() {
        $this->object->forceResult(TRUE)->notEmpty();
        $this->assertTrue($this->object->evaluate(''));
    }

    public function testForceResultFalse() {
        $this->object->notEmpty()->forceResult(FALSE);
        $this->assertFalse($this->object->evaluate('x'));
    }

    /**
     * @todo Implement testIpV4Address().
     */
    public function testIpV4Address()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testIpV6Address().
     */
    public function testIpV6Address()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testIpV4Netmask().
     */
    public function testIpV4Netmask()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testIpV6Netmask().
     */
    public function testIpV6Netmask()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }



}

?>
