<?php
/**
 * @package Tests
 * @subpackage Unit
 */

/**
 * Test class for NethGui_Core_Validator.
 * Generated by PHPUnit on 2011-04-01 at 16:22:41.
 * @package Tests
 * @subpackage Unit
 */
class NethGui_Core_ViewToJsonTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var NethGui_Core_View
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->module = new Tests_Unit_Core_ModuleClientAdapter();
        $this->module->initialize();
        $this->object = new NethGui_Core_View($this->module);
        $this->module->prepareView($this->object, 0);
    }

    public function testToJson()
    {
        $json = $this->object->toJson();

        $this->assertInternalType('string', $json);

        $a = json_decode($json, TRUE);

        $this->assertInternalType('array', $a);

        $expected = array(
            'a' => array('A', 'AA', 'AAA'),
            '__invalidParameters' => array(),
            'b' => '10.2',
            'c' => array('C', 'CC', 'CCC', 'CCCC', array('X')),            
        );        

        $this->assertEquals($expected, $a);
    }

}

class Tests_Unit_Core_ModuleClientAdapter extends NethGui_Core_Module_Standard //implements NethGui_Core_ClientAdapterInterface
{

    public function initialize()
    {
        parent::initialize();

        $this->parameters['a'] = array('A', 'AA', 'AAA');
        $this->parameters['b'] = '10.2';
        $this->parameters['c'] = new ArrayObject(array('C', 'CC', 'CCC', 'CCCC', new ArrayObject(array('X'))));        

    }

//    public function prepareViewForClient(NethGui_Core_ViewInterface $view)
//    {
//        unset($view['__unset']);        
//        $view['c0'] = $view['c']->getArrayCopy();
//        $view['c1'] = clone $view['c'];
//        unset($view['c']);
//        $view['a'] = implode(',', $view['a']);
//    }

}
