<?php
/**
 * @package Tests
 * @subpackage Unit
 */

/**
 * Test class for Nethgui_Core_View.
 * Generated by PHPUnit on 2011-04-01 at 16:22:41.
 * @package Tests
 * @subpackage Unit
 */
class Nethgui_Core_ViewClientEventsTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Nethgui_Core_View
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->module = new Test_Unit_Nethgui_Core_ModuleClientAdapter();
        $this->module->initialize();
        $this->object = new Nethgui_Core_View($this->module);
        $this->module->prepareView($this->object, 0);
    }

    public function testGetClientEvents()
    {
        $events = $this->object->getClientEvents();

        $this->assertInternalType('array', $events);

        $expected = array(
            array(
                'ID_a',
                array('A', 'AA', 'AAA')
            ),
            array(
                'ID_b',
                '10.2'
            ),
            array(
                'ID_c',
                array('C', 'CC', 'CCC', 'CCCC', array('X'))
            ),
            array(
                'ID___invalidParameters',
                array()
            )
        );

        $this->assertEquals($expected, $events);
    }

}

/**
 * @ignore
 */
class Test_Unit_Nethgui_Core_ModuleClientAdapter extends Nethgui_Core_Module_Standard
{

    public function __construct($identifier = NULL)
    {
        parent::__construct('ID');
    }

    public function initialize()
    {
        parent::initialize();

        $this->parameters['a'] = array('A', 'AA', 'AAA');
        $this->parameters['b'] = '10.2';
        $this->parameters['c'] = new ArrayObject(array('C', 'CC', 'CCC', 'CCCC', new ArrayObject(array('X'))));
    }

}
